accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),


    
]

eNotice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . views import index as home_view


app_name = 'eNotice'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),

    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.notice_list_view, name='home'),
    path('<int:notice_id>/', views.notice_view, name='notice_view'),
    path('new/', views.new_notice_page, name='new_notice'),
    path('u/<str:username>/', views.user_notice_list_view, name='user_notices'),
    path('save/<int:notice_id>/', views.save_notice, name='save_notice'),
    path('remove/<int:notice_id>/', views.remove_saved_notice, name='remove_saved_notice'),
    path('saved/', views.saved_notice_list_view, name='saved_notice_list'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1','password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login,logout
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

# Create your views here.

def index(request):
    return render(request, 'accounts/index.html')
def signup(request):
    if request.user.is_authenticated:
        return redirect('notices:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('notices:home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'accounts/my_account.html'
    success_url = reverse_lazy('accounts:my_account')
    
    def get_object(self):
        return self.request.user



@login_required
def custom_logout_view(request):
    logout(request)
    return redirect('home')

accounts/templates/accounts/accounts_layout.html
{% extends 'notices/base.html' %} {% load static %} {% block title %}
{% endblock%} {% block content %}

<button
  data-drawer-target="cta-button-sidebar"
  data-drawer-toggle="cta-button-sidebar"
  aria-controls="cta-button-sidebar"
  type="button"
  class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
>
  <span class="sr-only">Open sidebar</span>
  <svg
    class="w-6 h-6"
    aria-hidden="true"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      fill-rule="evenodd"
      d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"
    ></path>
  </svg>
</button>

<aside
  id="cta-button-sidebar"
  class="fixed top-20 left-0 z-40 w-64 h-screen overflow-y-auto transition-transform -translate-x-full sm:translate-x-0"
>
  <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
      <li>
        <a
          href="{% url 'accounts:index' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="size-6"
          >
            <path
              fill-rule="evenodd"
              d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z"
              clip-rule="evenodd"
            />
          </svg>

          <span class="ms-3">User Details</span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'accounts:my_account' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="size-6"
          >
            <path
              d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32l8.4-8.4Z"
            />
            <path
              d="M5.25 5.25a3 3 0 0 0-3 3v10.5a3 3 0 0 0 3 3h10.5a3 3 0 0 0 3-3V13.5a.75.75 0 0 0-1.5 0v5.25a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V8.25a1.5 1.5 0 0 1 1.5-1.5h5.25a.75.75 0 0 0 0-1.5H5.25Z"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Edit Profile</span>
        </a>
      </li>

      <li>
        <a
          href="{% url 'notices:new_notice' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="size-6"
          >
            <path
              fill-rule="evenodd"
              d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 9a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V15a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V9Z"
              clip-rule="evenodd"
            />
          </svg>

          <span class="flex-1 ms-3 whitespace-nowrap">New Notice</span>
        </a>
      </li>

      <li>
        <form
          action="{% url 'accounts:logout' %}"
          method="post"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          {% csrf_token %}
          <button type="submit" class="flex items-center w-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              class="w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            >
              <path
                fill-rule="evenodd"
                d="M16.5 3.75a1.5 1.5 0 0 1 1.5 1.5v13.5a1.5 1.5 0 0 1-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5V15a.75.75 0 0 0-1.5 0v3.75a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V5.25a3 3 0 0 0-3-3h-6a3 3 0 0 0-3 3V9A.75.75 0 1 0 9 9V5.25a1.5 1.5 0 0 1 1.5-1.5h6ZM5.78 8.47a.75.75 0 0 0-1.06 0l-3 3a.75.75 0 0 0 0 1.06l3 3a.75.75 0 0 0 1.06-1.06l-1.72-1.72H15a.75.75 0 0 0 0-1.5H4.06l1.72-1.72a.75.75 0 0 0 0-1.06Z"
                clip-rule="evenodd"
              />
            </svg>
            <span class="ms-3 whitespace-nowrap">Sign Out</span>
          </button>
        </form>
      </li>
    </ul>
    <div
      id="dropdown-cta"
      class="p-4 mt-6 rounded-lg bg-blue-50 dark:bg-blue-900"
      role="alert"
    >
      <div class="flex items-center mb-3">
        <span
          class="bg-orange-100 text-orange-800 text-sm font-semibold me-2 px-2.5 py-0.5 rounded dark:bg-orange-200 dark:text-orange-900"
          >Note</span
        >
      </div>
      <p class="mb-3 text-sm text-blue-800 dark:text-blue-400">
        Review eNotice Privacy Policy and Terms and Conditions! You can access
        these documents anytime in your profile settings.
      </p>
      <a
        class="text-sm text-blue-800 underline font-medium hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300"
        href="#"
        >Privacy Policy</a
      >
    </div>
  </div>
</aside>

<div class="p-4 sm:ml-64">
  <div
    class="p-4 border-2 border-gray-200 dark:border-gray-700 border-dashed rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-200"
  >
    {% block account_content %} {% endblock %}
  </div>
</div>

{% endblock %} {% block footer%} {% endblock %} {% block extra_scripts %}
<script src="{% static 'accounts/js/sidebar.js'%}"></script>

{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/accounts_layout.html' %} 
{% block title %}User Details{% endblock %} {% block account_content %}

<div class="bg-gray-900 text-white py-12 px-4 md:px-0">
  <div class="max-w-4xl mx-auto">
    <h1 class="text-3xl font-bold mb-4">My Account</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="p-4 md:p-6 bg-gray-800 rounded-lg shadow-md">
        <p class="text-lg mb-2">
          <span class="text-gray-400">User Name:</span> {{ user.username }}
        </p>
        <p class="text-lg mb-2">
          <span class="text-gray-400">First Name:</span> {{ user.first_name }}
        </p>
        <p class="text-lg mb-2">
          <span class="text-gray-400">Last Name:</span> {{ user.last_name }}
        </p>
        <p class="text-lg mb-2">
          <span class="text-gray-400">Email:</span> {{ user.email }}
        </p>
        <p class="text-lg mb-2">
          <span class="text-gray-400">User ID:</span> {{ user.id }}
        </p>
        <p class="text-lg mb-2">
          <span class="text-gray-400">Last Login:</span> {{ user.last_login }}
        </p>
      </div>
      <div class="relative hidden md:block">
        <svg
          class="absolute top-0 right-0 h-full w-full"
          viewBox="0 0 200 200"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle cx="100" cy="100" r="100" fill="rgba(29, 78, 216, 0.5)" />
        </svg>
        <div class="relative z-10 p-6 bg-gray-900 rounded-lg shadow-md">
          <p class="text-lg mb-2">
            <span class="text-gray-400">User Name:</span> {{ user.username }}
          </p>
          <p class="text-lg mb-2">
            <span class="text-gray-400">First Name:</span> {{ user.first_name }}
          </p>
          <p class="text-lg mb-2">
            <span class="text-gray-400">Last Name:</span> {{ user.last_name }}
          </p>
          <p class="text-lg mb-2">
            <span class="text-gray-400">Email:</span> {{ user.email }}
          </p>

          <p class="text-lg mb-2">
            <span class="text-gray-400">User ID:</span> {{ user.id }}
          </p>
          <p class="text-lg mb-2">
            <span class="text-gray-400">Last Login:</span> {{ user.last_login }}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    {% tailwind_css %}
  </head>
  <body class="bg-gray-50 dark:bg-gray-900">
    <section
      class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
    >
      <div
        class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
      >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <h1
            class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
          >
            Sign in to your account
          </h1>
          <form method="post" class="space-y-4 md:space-y-6">
            {% csrf_token %}
            <div>
              <label
                for="{{ form.username.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                >Username</label
              >
              <input
                type="text"
                name="{{ form.username.name }}"
                id="{{ form.username.id_for_label }}"
                class="bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter username..."
                required=""
              />
            </div>
            <div>
              <label
                for="{{ form.password.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                >Password</label
              >
              <input
                type="password"
                name="{{ form.password.name }}"
                id="{{ form.password.id_for_label }}"
                class="bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="••••••••"
                required=""
                autocomplete="new-password"
              />
            </div>

            <div class="flex items-center justify-between">
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input
                    id="remember"
                    aria-describedby="remember"
                    type="checkbox"
                    class="w-4 h-4 border border-gray-300 rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 focus:ring-3 focus:ring-primary-300 dark:ring-offset-gray-800 dark:focus:ring-primary-600"
                  />
                </div>
                <div class="ml-3 text-sm">
                  <label for="remember" class="text-blue-500 dark:text-grey-300"
                    >Remember me</label
                  >
                </div>
              </div>
              <a
                href="#"
                class="text-sm font-medium text-primary-600 hover:underline dark:text-sky-500"
                >Forgot password?</a
              >
            </div>
            <button
              type="submit"
              class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-primary-800"
            >
              Sign in
            </button>
            <p class="text-sm font-light text-gray-500 dark:text-gray-400">
              Don’t have an account yet?
              <a
                href="{% url 'accounts:signup' %}"
                class="font-medium text-primary-600 hover:underline dark:text-sky-500"
                >Sign up</a
              >
            </p>
          </form>
        </div>
      </div>
    </section>
  </body>
</html>

accounts/templates/accounts/my_account.html
{% extends 'accounts/accounts_layout.html' %}

{% block title %}Edit Details{% endblock %}


{% block account_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-6">
            <label for="{{ form.first_name.id_for_label }}" class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white">First Name</label>
            <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}"
                   class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                   placeholder="Enter first name..." value="{{ form.first_name.value }}">
        </div>
        
        <div class="mb-6">
            <label for="{{ form.last_name.id_for_label }}" class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white">Last Name</label>
            <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}"
                   class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                   placeholder="Enter last name..." value="{{ form.last_name.value }}">
        </div>
        
        <div class="mb-6">
            <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white">Email</label>
            <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}"
                   class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                   placeholder="Enter email..." value="{{ form.email.value }}">
        </div>
        
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Save Changes</button>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html>
  <head>
    <title>Sign Up</title>
    {% tailwind_css %}
  </head>
  <body class="bg-gray-50 dark:bg-gray-900">
    <div
      class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
    >
      <div
        class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
      >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <h1
            class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
          >
            Sign Up
          </h1>
          <form
            method="post"
            enctype="multipart/form-data"
            class="space-y-4 md:space-y-6"
          >
            {% csrf_token %}

            <div class="mb-6">
              <label
                for="{{ form.first_name.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >First Name</label
              >
              <input
                type="text"
                name="{{ form.first_name.name }}"
                id="{{ form.first_name.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter first name..."
                value="{{ form.first_name.value }}"
              />
            </div>

            <div class="mb-6">
              <label
                for="{{ form.last_name.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >Last Name</label
              >
              <input
                type="text"
                name="{{ form.last_name.name }}"
                id="{{ form.last_name.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter last name..."
                value="{{ form.last_name.value }}"
              />
            </div>

            <div class="mb-6">
              <label
                for="{{ form.username.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >Username</label
              >
              <input
                type="text"
                name="{{ form.username.name }}"
                id="{{ form.username.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter username..."
                value="{{ form.username.value }}"
              />
            </div>

            <div class="mb-6">
              <label
                for="{{ form.email.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >Email</label
              >
              <input
                type="email"
                name="{{ form.email.name }}"
                id="{{ form.email.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter email..."
                value="{{ form.email.value }}"
              />
            </div>

            <div class="mb-6">
              <label
                for="{{ form.password1.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >Password</label
              >
              <input
                type="password"
                name="{{ form.password1.name }}"
                id="{{ form.password1.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Enter password..."
              />
            </div>

            <div class="mb-6">
              <label
                for="{{ form.password2.id_for_label }}"
                class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
                >Confirm Password</label
              >
              <input
                type="password"
                name="{{ form.password2.name }}"
                id="{{ form.password2.id_for_label }}"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Confirm password..."
              />
            </div>

            <button
              type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            >
              Sign Up
            </button>
          </form>
          <p class="text-sm font-light text-gray-500 dark:text-gray-400">
            Already have an account?
            <a
              href="{% url 'accounts:login' %}"
              class="font-medium text-blue-600 hover:underline dark:text-blue-500"
              >Login here</a
            >
          </p>
        </div>
      </div>
    </div>
  </body>
</html>