accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),


    
]

eNotice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . views import index as home_view


app_name = 'eNotice'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),

    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.notice_list_view, name='home'),
    path('<int:notice_id>/', views.notice_view, name='notice_view'),
    path('new/', views.new_notice_page, name='new_notice'),
    path('u/<str:username>/', views.user_notice_list_view, name='user_notices'),
    path('save/<int:notice_id>/', views.save_notice, name='save_notice'),
    path('remove/<int:notice_id>/', views.remove_saved_notice, name='remove_saved_notice'),
    path('saved/', views.saved_notice_list_view, name='saved_notice_list'),
]

notices/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Notice(models.Model):
    title = models.CharField(max_length=100)
    message = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.DO_NOTHING)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    document = models.FileField(upload_to='documents/', null=True, blank=True)

    def __str__(self):
        return self.title


class SavedNotice(models.Model):
    user = models.ForeignKey(User, related_name='saved_notices', on_delete=models.CASCADE)
    notice = models.ForeignKey(Notice, related_name='saved_by_users', on_delete=models.CASCADE)
    saved_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'notice')

    def __str__(self):
        return f"{self.user.username} saved {self.notice.title}"

notices/forms.py
from django import forms
from .models import Notice

class NewNoticeForm(forms.ModelForm):

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'Write your message here...'}
        ),
        max_length=2000,
        help_text='The max length of the text is 2000.'
    )

    class Meta:
        model = Notice
        fields = ['title', 'message', 'image', 'video', 'document']
        labels = {
            'title': 'Title',
            'image': 'Image (SVG, PNG, JPG, GIF up to 800x400px)',
            'video': 'Video (MP4, MOV, AVI up to 50MB)',
            'document': 'Document (PDF, DOCX, TXT up to 5MB)'
        }
        help_texts = {
            'image': 'Allowed formats: SVG, PNG, JPG, GIF. Maximum resolution: 800x400 pixels.',
            'video': 'Allowed formats: MP4, MOV, AVI. Maximum file size: 50MB.',
            'document': 'Allowed formats: PDF, DOCX, TXT. Maximum file size: 5MB.'
        }

notices/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import Notice, User, SavedNotice
from .forms import NewNoticeForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required
def notice_list_view(request):
    notices_list = Notice.objects.order_by('-created_at')
    paginator = Paginator(notices_list, 10)  # Show 10 notices per page

    page = request.GET.get('page')
    try:
        notices = paginator.page(page)
    except PageNotAnInteger:
        notices = paginator.page(1)
    except EmptyPage:
        notices = paginator.page(paginator.num_pages)

 
    for notice in notices:
        notice.is_saved = SavedNotice.objects.filter(user=request.user, notice=notice).exists()

    return render(request, 'notices/home.html', {'notices': notices})


@login_required
def user_notice_list_view(request, username):
    user = get_object_or_404(User, username=username)
    notices_list = Notice.objects.filter(created_by=user).order_by('-created_at')
    paginator = Paginator(notices_list, 10)

    page = request.GET.get('page')
    try:
        notices = paginator.page(page)
    except PageNotAnInteger:
        notices = paginator.page(1)
    except EmptyPage:
        notices = paginator.page(paginator.num_pages)

    return render(request, 'notices/notices_by_user.html', {'notices': notices, 'user': user})

@login_required
def notice_view(request, notice_id):
    notice = get_object_or_404(Notice, id=notice_id)
    is_saved = SavedNotice.objects.filter(user=request.user, notice=notice).exists()
    return render(request, 'notices/notice_page.html', {'notice': notice, 'is_saved': is_saved})

@login_required
def save_notice(request, notice_id):
    notice = get_object_or_404(Notice, id=notice_id)
    SavedNotice.objects.get_or_create(user=request.user, notice=notice)
    return redirect('notices:notice_view', notice_id=notice.id)

@login_required
def remove_saved_notice(request, notice_id):
    notice = get_object_or_404(Notice, id=notice_id)
    SavedNotice.objects.filter(user=request.user, notice=notice).delete()
    return redirect('notices:notice_view', notice_id=notice.id)

@login_required
def saved_notice_list_view(request):
    saved_notices_list = SavedNotice.objects.filter(user=request.user).select_related('notice').order_by('-saved_at')
    paginator = Paginator(saved_notices_list, 9)

    page = request.GET.get('page')
    try:
        saved_notices = paginator.page(page)
    except PageNotAnInteger:
        saved_notices = paginator.page(1)
    except EmptyPage:
        saved_notices = paginator.page(paginator.num_pages)

    return render(request, 'notices/saved_notice_list.html', {'saved_notices': saved_notices})

@staff_member_required
def new_notice_page(request):
    if request.method == 'POST':
        form = NewNoticeForm(request.POST, request.FILES)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.created_by = request.user
            notice.save()
            return redirect('notices:notice_view', notice_id=notice.pk)
    else:
        form = NewNoticeForm()
    return render(request, 'notices/new_notice.html', {'form': form})

notices/templates/notices/base.html
{% load static tailwind_tags %} {% load static %}

<!DOCTYPE html>
<html lang="en" class="light-mode">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    {% tailwind_css %} {% block extra_head %}{% endblock %}
  </head>
  <body class="bg-gray-100 dark:bg-gray-900 px-4 sm:px-8 lg:px-10">
    <header class="bg-white shadow-sm sticky top-0 z-50">
      <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div
          class="max-w-screen-xl flex items-center justify-between mx-auto p-4 py-6"
        >
          <a
            href="{% url 'home' %}"
            class="flex items-center space-x-3 rtl:space-x-reverse"
          >
            <img
              src="{% static 'notices/img/logo.png' %}"
              class="h-6"
              alt="eNotice Logo"
            />
            <span
              class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"
              >Notice</span
            >
          </a>
          <!-- User Menu Button and Dropdown -->
          <div class="relative">
            {% load static %}

            <button
              id="user-menu-button"
              class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
              aria-expanded="false"
              aria-haspopup="true"
            >
              <span class="sr-only">Open user menu</span>
              <div
                class="w-8 h-8 rounded-full bg-gray-500 flex items-center justify-center text-white font-bold"
              >
                {{ user.first_name|slice:":1" }}{{ user.last_name|slice:":1" }}
              </div>
            </button>

            <!-- User Dropdown menu -->
            <div
              id="user-dropdown"
              class="absolute right-0 z-50 hidden mt-2 w-48 bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
            >
              <div class="px-4 py-3">
                <span class="block text-sm text-gray-900 dark:text-white"
                  >{{ user.username }}</span
                >
                <span
                  class="block text-sm text-gray-500 truncate dark:text-gray-400"
                  >{{ user.email }}</span
                >
              </div>
              <ul class="py-2" aria-labelledby="user-menu-button">
                <li>
                  <a
                    href="{% url 'accounts:index' %}"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                    >Dashboard</a
                  >
                </li>
                <li>
                  <a
                    href="{% url 'notices:new_notice' %}"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                    >New Notice</a
                  >
                </li>
                <li>
                  <a
                    href="{% url 'notices:saved_notice_list' %}"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                    >Saved</a
                  >
                </li>
                <li>
                  <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button
                      type="submit"
                      class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                    >
                      Logout
                    </button>
                  </form>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>

      <script src="{% static 'notices/js/user-dropdown.js'%}"></script>
    </header>

    <main class="container mx-auto mt-8">
      {% block content %}

      <!-- Default content -->
       
      {% endblock %}
    </main>

    {% block footer%}
    <footer class="bg-white rounded-lg shadow dark:bg-gray-900 m-4">
      <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <hr
          class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8"
        />
        <span
          class="block text-sm text-gray-500 sm:text-center dark:text-gray-400"
          >© {% now "Y" %}<a
            href="https://flowbite.com/"
            class="hover:underline"
          >
            eNotice</a
          >. All Rights Reserved. Developed By Rawal</span
        >
      </div>
    </footer>
    {% endblock %} {% block extra_scripts %} {% endblock %}
  </body>
</html>

notices/templates/notices/new_notice.html
{% extends 'accounts/accounts_layout.html' %} {% block title %}New Notice{%
endblock %} {% block extra_head %}
<style></style>
{% endblock %} {% block account_content %}

<h2
  class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white"
>
  New Notice
</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="mb-6">
    <label
      for="id_title"
      class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
      >Title</label
    >
    <input
      type="text"
      name="title"
      id="id_title"
      class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      placeholder="Enter title..."
    />
  </div>

  <div class="mb-6">
    <label
      for="id_message"
      class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
      >Message</label
    >
    <textarea
      name="message"
      id="id_message"
      rows="4"
      class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 rounded-lg text-sm text-gray-900 p-2.5 focus:ring-blue-500 focus:border-blue-500 block dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      placeholder="Write your message here..."
    ></textarea>
    <p class="mt-1 text-sm text-gray-500 dark:text-gray-300">
      The max length of the text is 2000.
    </p>
  </div>

  <!-- Image field -->
  <div class="mb-4">
    <label
      for="id_image"
      class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
      >Image</label
    >
    <input
      type="file"
      name="image"
      id="id_image"
      class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-sm text-gray-900 rounded-lg cursor-pointer focus:outline-none p-2.5 dark:text-gray-400 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
      aria-describedby="file_input_help"
    />
    <p
      class="mt-1 text-sm text-gray-500 dark:text-gray-300"
      id="file_input_help"
    >
      Allowed formats: SVG, PNG, JPG, GIF (MAX. 800x400px).
    </p>
  </div>

  <!-- Video field -->
  <div class="mb-4">
    <label
      for="id_video"
      class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
      >Video</label
    >
    <input
      type="file"
      name="video"
      id="id_video"
      class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-sm text-gray-900 rounded-lg cursor-pointer focus:outline-none p-2.5 dark:text-gray-400 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
      aria-describedby="file_input_help"
    />
    <p
      class="mt-1 text-sm text-gray-500 dark:text-gray-300"
      id="file_input_help"
    >
      Allowed formats: MP4, MOV, AVI (MAX. 50MB).
    </p>
  </div>

  <!-- Document field -->
  <div class="mb-4">
    <label
      for="id_document"
      class="block mb-2 text-sm font-extrabold text-gray-900 dark:text-white"
      >Document</label
    >
    <input
      type="file"
      name="document"
      id="id_document"
      class="w-full sm:w-2/3 bg-gray-50 border border-gray-300 text-sm text-gray-900 rounded-lg cursor-pointer focus:outline-none p-2.5 dark:text-gray-400 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
      aria-describedby="file_input_help"
    />
    <p
      class="mt-1 text-sm text-gray-500 dark:text-gray-300"
      id="file_input_help"
    >
      Allowed formats: PDF, DOCX, TXT (MAX. 5MB).
    </p>
  </div>

  <div class="mt-6">
    <button
      type="submit"
      class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
    >
      Create
    </button>
  </div>
</form>

{% endblock %} {% block footer%} {% endblock %}

notices/templates/notices/notice_page.html
{% extends 'notices/base.html' %} {% block title %}{{ notice.title }} -
Notices{% endblock %} {% block content %}
<main
  class="pt-8 pb-16 lg:pt-16 lg:pb-24 bg-white dark:bg-gray-900 antialiased"
>
  <div class="flex justify-between px-4 mx-auto max-w-screen-xl">
    <article
      class="mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert"
    >
      <header class="mb-4 lg:mb-6 not-format">
        <address class="flex items-center mb-6 not-italic">
          <div
            class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white"
          >
            <img
              class="mr-4 w-16 h-16 rounded-full"
              src="https://flowbite.com/docs/images/people/profile-picture-2.jpg"
              alt="Jese Leos"
            />
            <div>
              <a
                href="{% url 'notices:user_notices' notice.created_by.username %}"
                rel="author"
                class="text-xl font-bold"
                >{{ notice.created_by.username }}</a
              >
              <p class="text-base text-gray-500 dark:text-gray-400">
                Member Of ISP Announcement Department
              </p>
              <p class="text-base text-gray-500 dark:text-gray-400">
                <time pubdate datetime="2022-02-08" title=""
                  >{{ notice.created_at|date:"F Y" }}</time
                >
              </p>
            </div>
          </div>
        </address>
        <h1
          class="mb-4 text-3xl font-extrabold leading-tight text-gray-900 lg:mb-6 dark:text-white"
        >
          {{ notice.title }}
        </h1>
      </header>
      {% if notice.image %}
      <div class="pb-4">
        <img
          class="h-auto max-w-full"
          src="{{ notice.image.url }}"
          alt="image description"
        />
      </div>
      {% endif %}
      <div class="p-4 border-t border-b border-gray-300">
        <p class="text-gray-900 dark:text-white">{{ notice.message }}</p>
      </div>
      {% if notice.document %}
      <div
        class="flex items-center justify-between p-4 border-b border-gray-300"
      >
        <div>
          <p class="text-sm font-medium text-gray-500 dark:text-gray-400">
            Download Attachment:
          </p>
          <a
            href="{{ notice.document.url }}"
            class="flex items-center space-x-2 text-gray-900 dark:text-white hover:text-blue-500"
          >
            <svg
              class="w-5 h-5 fill-current"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-6"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3"
              />
            </svg>

            <span>Download File</span>
          </a>
        </div>
      </div>
      {% endif %} {% if notice.video %}
      <div class="p-4">
        <video class="w-full" autoplay controls>
          <source src="{{ notice.video.url }}" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>
      {% endif %}
    </article>
  </div>
</main>
{% endblock %}

notices/templates/notices/saved_notice_list.html
{% extends 'notices/base.html' %} {% block content %}
<nav class="flex mb-4" aria-label="Breadcrumb">
  <ol
    class="inline-flex items-center space-x-1 md:space-x-3 rtl:space-x-reverse"
  >
    <li class="inline-flex items-center">
      <a
        href="#"
        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white"
      >
        <svg
          class="w-3 h-3 me-2.5"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path
            d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"
          />
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg
          class="w-3 h-3 text-gray-400 mx-1 rtl:rotate-180"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 6 10"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="m1 9 4-4-4-4"
          />
        </svg>
        <a
          href="#"
          class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"
          >Notices</a
        >
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg
          class="w-3 h-3 text-gray-400 mx-1 rtl:rotate-180"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 6 10"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="m1 9 4-4-4-4"
          />
        </svg>

        <span
          class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400"
          >Saved</span
        >
      </div>
    </li>
  </ol>
</nav>
{% if saved_notices %}
<h2
  class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white"
>
  {{ saved_notices|length }} Saved Notices
</h2>
{% endif %}

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
  {% for saved_notice in saved_notices %}
  <div
    class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
  >
    <a href="{% url 'notices:remove_saved_notice' saved_notice.notice.id %}">
      <h5
        class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
      >
        {{ saved_notice.notice.title }}
      </h5>
    </a>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
      {{ saved_notice.notice.message|slice:":200" }} 
      {% if saved_notice.notice.message|length > 200 %}... {% endif %}
    </p>
    <a
      href="{% url 'notices:remove_saved_notice' saved_notice.notice.id %}"
      class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    >
      Read more
      <svg
        class="rtl:rotate-180 w-3.5 h-3.5 ms-2"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 14 10"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 5h12m0 0L9 1m4 4L9 9"
        />
      </svg>
    </a>
  </div>
  {% endfor %}
</div>

<nav aria-label="Page navigation" class="mt-4">
  <ul class="flex space-x-1 text-sm">
    {% if saved_notices.has_previous %}
    <li>
      <a
        href="?page=1"
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-gray-100 hover:text-gray-700"
      >
        &laquo; First
      </a>
    </li>
    <li>
      <a
        href="?page={{ saved_notices.previous_page_number }}"
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-gray-100 hover:text-gray-700"
      >
        Previous
      </a>
    </li>
    {% else %}
    <li>
      <span
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-300 bg-white border border-gray-300 rounded-l-lg"
        style="color: black"
      >
        &laquo; First
      </span>
    </li>
    <li>
      <span
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-300 bg-white border border-gray-300"
        style="color: black"
      >
        Previous
      </span>
    </li>
    {% endif %} {% for i in saved_notices.paginator.page_range %}
    <li>
      {% if saved_notices.number == i %}
      <span
        class="flex items-center justify-center px-3 h-8 leading-tight text-blue-600 bg-blue-50 border border-gray-300 dark:bg-gray-700 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-blue-100 hover:text-blue-700"
      >
        {{ i }}
      </span>
      {% else %}
      <a
        href="?page={{ i }}"
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-gray-100 hover:text-gray-700"
      >
        {{ i }}
      </a>
      {% endif %}
    </li>
    {% endfor %} {% if saved_notices.has_next %}
    <li>
      <a
        href="?page={{ saved_notices.next_page_number }}"
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-gray-100 hover:text-gray-700"
      >
        Next
      </a>
    </li>
    <li>
      <a
        href="?page={{ saved_notices.paginator.num_pages }}"
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white hover:bg-gray-100 hover:text-gray-700"
      >
        Last &raquo;
      </a>
    </li>
    {% else %}
    <li>
      <span
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-300 bg-white border border-gray-300"
        style="color: black"
      >
        Next
      </span>
    </li>
    <li>
      <span
        class="flex items-center justify-center px-3 h-8 leading-tight text-gray-300 bg-white border border-gray-300 rounded-r-lg"
        style="color: black"
      >
        Last &raquo;
      </span>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}